more details, [promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)

fetch("some url").then().catch().finally()



promise
- an object representing the eventual completion or failure of an asynchronous operation
- states
	- pending
	- fulfilled
	- rejected
- Q and bluebird promise libraries were used.
- [Read this article](https://blog.kuzzle.io/bluebird-native-async_await-javascript-promises-performances-2020)
- Promise(function(resolve, reject))
- `then` is associated with `resolve`

```javascript
const promiseOne = new Promise((resolve, reject) => {
    // do an async task
    // e.g. DB queries,  cryptography calls, network requests
    setTimeout(() => {
        console.log("Async task1 is complete");
        resolve(); // this is must to resolve the promise
    }, 1000);
});

promiseOne.then(() => console.log("Promise1 is consumed"));

// another way
new Promise((resolve, reject) => {
    setTimeout(() => {
        console.log("Async task2 is complete");
        resolve();
    }, 500);
}).then(() => console.log("Promise2 is consumed"));
```

passing value using resolve()
```js
const promiseThree = new Promise(function (resolve, reject) {
    setTimeout(function () {
        resolve({
            userName: "Raghav",
            email: "raghav@example.com"
        });
    }, 1000)
});

promiseThree.then(function(user) {
    console.log("Promise3 is consumed. Received user from promise:", user);
})
```

### chaining
getting a part of the object from a promise
```js
const promiseFour = new Promise((resolve, reject) => {
    setTimeout(() => {
        let error = true;
        if (!error) {
            resolve({
                userName: "Raghav",
                email: "raghav@example.com"
            });
        } else {
            reject("reject: Something went wrong")
        }
    }, 1000);
});

// this would result in error
const userName = promiseFour.then((user) => {
    console.log("Promise resolved: ", user);
    return user.userName;
});

console.log("userName ", userName);

output:
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "reject: Something went wrong".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

to handle this, you need chaining
```js
promiseFour.then((user) => {
    console.log("PromiseFour1 resolved: ", user);
    return user.userName;
}).then((userName) => { // if the response is successful
    console.log("PromiseFour2 resolved: ", userName);
}).catch((err) => { // if there is any error
    console.error("PromiseFour3 resolved: ", err);
}).finally(() => { // this will always be executed
    console.error("PromiseFour is either resolved or rejected");
});
```


### handling promise using async/await
this is another way to handle then().catch()

```js
const promiseFive = new Promise((resolve, reject) => {
    setTimeout(() => {
        let error = true;
        if (!error) {
            resolve({
                userName: "javascript",
                email: "js@example.com"
            });
        } else {
            reject("Error: JS went wrong")
        }
    }, 1000);
});

async function consumePromiseFive() {
    try {
        const responseFive = await promiseFive; // note: promise is an object
        console.log("responseFive : ", responseFive);
    } catch (err) {
        console.error("Error in consumePromiseFive() : ", err);
    }
}

consumePromiseFive();
```


### [using fetch](obsidian://open?vault=Documents&file=Obsidian%20Vault%2F1%20Personal%2Ftechnical%2Fcourses%2FFrontend%2Fjavascript%2F18.%20fetch)
fetch takes a promise
```js
async function getAllUsers() {
    try {
        const usersApiResponse = await fetch("https://jsonplaceholder.typicode.com/users")
        const usersData = await usersApiResponse.json(); // to convert to JSON will take some time, so need an await
        console.log(usersData);
    } catch (err) {
        console.error("Error in getAllUsers() : ", err);
    }
}

getAllUsers();
```


without using any function, you can directly use fetch
```js
fetch("https://jsonplaceholder.typicode.com/users")
    .then((userApiResponse) => {
        return userApiResponse.json();
    }).then((usersData) => {
        console.log(usersData);
    }).catch((err) => {
        console.error(err);
    });
```

